### ISSUE TITLE
Support for iPhone 11 and above

### ISSUE THREAD

**Issue by devth** [wernjie/digital-scale-plus#1]

**Comment by wxwern** [comment]
Hi @devth,

Unfortunately, the iPhone 11 does not have the hardware capability needed for this web app to function - 3D Touch. This means that iPhone 11 support is impossible. 

Furthermore, unless Apple decides to include 3D Touch in new iPhone models, all iPhone 11 and later models won't be compatible with this web app. As noted in `README.md`, only the iPhone 6S, 7, 8, X and XS are supported.

Thank you, and hope this clarifies! :)
